// <auto-generated />
using System;
using InventoryWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryWebApp.Migrations
{
    [DbContext(typeof(InventoryDBContext))]
    [Migration("20250906203603_removed image in model")]
    partial class removedimageinmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("InventoryWebApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 6, 20, 36, 2, 569, DateTimeKind.Utc).AddTicks(9712),
                            Description = "High performance laptop for developers",
                            Name = "Laptop",
                            Price = 28000.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 6, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(691),
                            Description = "Latest generation flagship smartphone",
                            Name = "Smartphone",
                            Price = 22000.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 6, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(693),
                            Description = "Noise-cancelling over-ear headphones",
                            Name = "Headphones",
                            Price = 899.99m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 6, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(694),
                            Description = "RGB backlit mechanical keyboard with blue switches",
                            Name = "Mechanical Keyboard",
                            Price = 1699.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 6, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(696),
                            Description = "High DPI wireless gaming mouse",
                            Name = "Gaming Mouse",
                            Price = 489.99m,
                            Stock = 30
                        });
                });

            modelBuilder.Entity("InventoryWebApp.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UnitsSold")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            PurchaseDate = new DateTime(2025, 8, 27, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(5583),
                            SellingPrice = 0m,
                            UnitsSold = 2
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 2,
                            PurchaseDate = new DateTime(2025, 8, 29, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(6121),
                            SellingPrice = 0m,
                            UnitsSold = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 3,
                            PurchaseDate = new DateTime(2025, 9, 1, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(6127),
                            SellingPrice = 0m,
                            UnitsSold = 3
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 4,
                            PurchaseDate = new DateTime(2025, 9, 3, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(6128),
                            SellingPrice = 0m,
                            UnitsSold = 1
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 5,
                            PurchaseDate = new DateTime(2025, 9, 5, 20, 36, 2, 570, DateTimeKind.Utc).AddTicks(6129),
                            SellingPrice = 0m,
                            UnitsSold = 4
                        });
                });

            modelBuilder.Entity("InventoryWebApp.Models.StockLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("NewStock")
                        .HasColumnType("int");

                    b.Property<int>("OldStock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("StockLogs");
                });

            modelBuilder.Entity("InventoryWebApp.Models.StockLog", b =>
                {
                    b.HasOne("InventoryWebApp.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });
#pragma warning restore 612, 618
        }
    }
}
